name: Build and publish

on:
  push:
    branches:
      - '**'

jobs:
  build_and_publish:
    uses: navikt/hag-workflows/.github/workflows/build_with_publish.yml@main
    permissions:
      packages: write
