name: Build and publish snapshot

on:
  push:
    branches:
      - dev/**

jobs:
  build_and_publish:
    uses: navikt/hag-workflows/.github/workflows/build_with_publish.yml@eksperiment
    permissions:
      packages: write
    with:
      publish-snapshot: true
